---
abstract: Date::Piece type and coercions for Moose.
author:
  - 'Steven Lee <stevenl@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Date-Piece
provides:
  MooseX::Types::Date::Piece:
    file: lib/MooseX/Types/Date/Piece.pm
    version: 0.01
requires:
  Date::Piece: v0.0.3
  Moose: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
